---
- name: Configure Apache2
  hosts: all
  become: yes
  tasks: 
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Edit Index.html
      ansible.builtin.copy:
        content: "Hello From Divyaraj"
        dest: /var/www/html/index.html
 
