---
- name: Play with become options
  hosts: all
  gather_facts: false
  become: yes
  # become_user: root
  # become_method: sudo  
  tasks:
    - name: Install nginx package
      ansible.builtin.apt:
        name:  nginx 
        state:  present
      # become: yes
      # become_user: root
      # become_method: sudo
